In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(arr)
print("Shape of the array is :",arr.shape)
print("The maximum element is : ",np.max(arr))
print("The minimum element is : ",np.min(arr))
print("The mean of elements is : ",np.mean(arr))
print("The standard deviation of elements is: ",np.std(arr))
newarr=arr.reshape(4,5)
print("The new reshaped array is: ", newarr)
print(newarr[1,:])
print(newarr[:,2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Shape of the array is : (20,)
The maximum element is :  20
The minimum element is :  1
The mean of elements is :  10.5
The standard deviation of elements is:  5.766281297335398
The new reshaped array is:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 6  7  8  9 10]
[ 3  8 13 18]


In [2]:
import numpy as np
A=np.array([10,20,30,40,50])
B=np.array([5,10,15,20,25])
print("Addition of arrays element wise: ",np.add(A,B))
print("Subtraction: ",np.subtract(B,A))
print("Multiplication  : ",np.multiply(A,B))
print("Division: ",np.divide(A,B))
print("Sum of all elemnts in A : ", np.sum(A))

Addition of arrays element wise:  [15 30 45 60 75]
Subtraction:  [ -5 -10 -15 -20 -25]
Multiplication  :  [  50  200  450  800 1250]
Division:  [2. 2. 2. 2. 2.]
Sum of all elemnts in A :  150


In [3]:
import pandas as pd
data={
    "Roll_No": [101,102,103,104,105],
    "Name":["Ravi","Priya","Kiran","Anu","Sita"],
    "Marks":[85,92,78,88,95]
}
df=pd.DataFrame(data)
print(df)
print("First 3 rows are : \n",df.loc[[0,1,2]])
print("Mean of marks:",df['Marks'].mean())
print("Top Student: ",df.loc[df['Marks'].idxmax(), 'Name'])
print("Least Student: ",df.loc[df['Marks'].idxmin(), 'Name'])
df=df.assign(Grade=['B','A','C','B','A'])
print(df)

   Roll_No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78
3      104    Anu     88
4      105   Sita     95
First 3 rows are : 
    Roll_No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78
Mean of marks: 87.6
Top Student:  Sita
Least Student:  Kiran
   Roll_No   Name  Marks Grade
0      101   Ravi     85     B
1      102  Priya     92     A
2      103  Kiran     78     C
3      104    Anu     88     B
4      105   Sita     95     A


In [4]:
import pandas as pd
data={
    "Product": ["Laptop","Mouse","Keyboard","Monitor"],
    "Price":[50000,500,1200,10000],
    "Quantity":[10,50,30,15]
}
df=pd.DataFrame(data)
print(df)
df['total_value'] = df['Quantity'] * df['Price']
print(df)
print("Product with high value: ",df.loc[df['total_value'].idxmax(), 'Product'])
print("Total Inventory Value : ",df['total_value'].sum())

    Product  Price  Quantity
0    Laptop  50000        10
1     Mouse    500        50
2  Keyboard   1200        30
3   Monitor  10000        15
    Product  Price  Quantity  total_value
0    Laptop  50000        10       500000
1     Mouse    500        50        25000
2  Keyboard   1200        30        36000
3   Monitor  10000        15       150000
Product with high value:  Laptop
Total Inventory Value :  711000


In [5]:
import pandas as pd
from sklearn.datasets import load_iris

# Load dataset
iris = load_iris()

# Create DataFrame
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Add target column
df['species'] = iris.target

# First 5 records
print("First 5 records:")
print(df.head())

# Shape
print("\nRows and Columns:")
print(df.shape)

# Column names
print("\nColumn Names:")
print(df.columns)

# Missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Summary statistics
print("\nSummary Statistics:")
print(df.describe())

# Class count
print("\nSamples in each class:")
print(df['species'].value_counts())

First 5 records:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0  

Rows and Columns:
(150, 5)

Column Names:
Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'species'],
      dtype='object')

Missing Values:
sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

Summary Statistics:
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000  